### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by bitsk** [sipeed/Longduino#1]
### Arduino core
 **wiring_digital.c** 
* ~~pinMode~~
* ~~digitalWrite~~
* ~~digitalRead~~  @Ldream 
* ~~digitalToggle~~  @Ldream 

**wiring_analog.c**
* ~~analogRead~~   @ReinForce-II
* ~~analogRefe1rence~~   @ReinForce-II
* ~~analogWrite~~ @ReinForce-II

**wiring_pulse.c**
* ~~pulseIn~~ @ReinForce-II
* ~~pulseInLong~~ @ReinForce-II

**wiring_shift.c**
* ~~shiftIn~~ @ReinForce-II
* ~~shiftOut~~ @ReinForce-II

**WInterrupts.c**
* ~~attachInterrupt~~ @ReinForce-II
* ~~attachInterruptParam~~ @ReinForce-II
* ~~detachInterrupt~~ @ReinForce-II

**Tone.cpp**
* tone
* noTone

**WMath.cpp**
* ~~random~~ @ReinForce-II
* ~~randomSeed~~ @ReinForce-II

**HardwareSerial.cpp**
* Class HardwareSerial

### Libraries

* Wire
* ~~SPI~~ @ReinForce-II
* LCD (Graphics library, need SPI)
* SD (need SPI)
* Ticker
* I2S
* ...

**Comment by bitsk** [comment]
可在此issue下回复认领项目

**Comment by aryedevops** [comment]
Hi, Great job on the Longduino.
I have ordered this board and I know that it comes with an 160x80 LCD. Can we use it with Arduino and Longduino?
The main idea was to be able to work with the LCD and I am not sure how to do that so far, Turning to your solution I hope to get the solution I am looking for. 
Can we Program the LCD that comes with it using Longduino?
Thanks

**Comment by ckuehnel** [comment]
Here is some info of my  first steps w/ this interesting part:https://ckblog2016.net/2020/06/27/sipeed-longan-nano/Dr. Claus Kühnel - Talstr. 13b - CH-8852 AltendorfMobile +41-76-3960801
-------- Ursprüngliche Nachricht --------Von: Arye DevOps <notifications@github.com> Datum: 06.09.20  03:56  (GMT+01:00) An: sipeed/Longduino <Longduino@noreply.github.com> Cc: Claus Kühnel <info@ckuehnel.ch>, Manual <manual@noreply.github.com> Betreff: Re: [sipeed/Longduino] TODO list (#1) 
Hi, Great job on the Longduino.
I have ordered this board and I know that it comes with an 160x80 LCD. Can we use it with Arduino and Longduino?
The main idea was to be able to work with the LCD and I am not sure how to do that so far, Turning to your solution I hope to get the solution I am looking for.
Can we Program the LCD that comes with it using Longduino?
Thanks

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sipeed/Longduino/issues/1#issuecomment-687686847",
"url": "https://github.com/sipeed/Longduino/issues/1#issuecomment-687686847",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by scpcom** [comment]
I added HardwareSerial and Adafruit_GFX implementations and examples for LCD, RGB LED and WiFi:
https://github.com/scpcom/Longduino/
SD/FATFS is also included, but I did not yet implement Arduino style class, it is just the code imported from Longan_GD32VF_examples.

Update 2020/11/01:
- Added SD and WiFiEsp Arduino C++ libraries modified for GD32V
- Sipeed_GD32V_LCD is now using SPI Arduino C++ library, does not need lcd C library anymore
- Added Arduino menu items to choose between 108MHz and 96MHz CPU clock
- Added USBCDC C library (USB Composite serial)

**Comment by scpcom** [comment]
Update 2020/11/20:
- core: implement Partition Scheme setting (allows bigger apps/sketches)
- core: Print: add printf (now also available on Streams/SD/Sipeed_GD32V_LCD etc.)
- core: WInterrupts: fix and use macros 
- core: add hooks
- core: add Tone
- variants: reduce PIN_MAP size
- GD32V: examples/GPIOInterrupt added
- Sipeed_GD32V_LCD: add color565
- Sipeed_GD32V_LCD: update, move and rename mock_ili9341 to mock_display
- fixed many compiler warnings

https://github.com/scpcom/Longduino/releases/tag/v0.1.7

**Comment by LenReinhart** [comment]
I have been struggling with my Nano. PlatformIO has not been successful and I have been unable to upload .bin files to it or use DFU. I had hoped this would at least get me the Ardunio environment. I am on Windows 10 Pro. My Device Manager shows two ports when I am using a USB to UART converter plugged into the com port on the end. If I use the USB the only thing that shows up is a line in Universal Serial Bus Controllers: GD32 Device in DFU mode after I do the boot/reset but no COM Port. It also doesn't show as a file under file manager.  I tried compiling and downloading Blink to both COM Ports and this is what I got:

C:\Users\Len\AppData\Local\Arduino15\packages\Longduino\hardware\gd32v\0.1.1\variants\sipeed-longan-nano\pins_arduino.c:48:31: warning: 'PIN_MAP' initialized and declared 'extern'
   48 | extern const gd32v_pin_info_t PIN_MAP[VARIANT_GPIO_NUM] = {
      |                               ^~~~~~~
Sketch uses 10725 bytes (16%) of program storage space. Maximum is 65536 bytes.
java.lang.NullPointerException
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingProgrammer(SerialUploader.java:295)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:90)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	at processing.app.SketchController.upload(SketchController.java:732)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$UploadHandler.run(Editor.java:2055)
	at java.lang.Thread.run(Thread.java:748)
