### ISSUE TITLE
[macOS]  Tool openocd is not available for your operating system.

### ISSUE THREAD

**Issue by KenjutsuGH** [sipeed/Longduino#15]
I am trying to add **Longduino (GD32V)** support via `Boards Manager` and get the following error:

```
Tool openocd is not available for your operating system.
java.lang.RuntimeException: java.lang.Exception: Tool openocd is not available for your operating system.
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:175)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Tool openocd is not available for your operating system.
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:89)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:172)
	... 1 more
```
My setup:
- macOS 10.13.6 (17G8037)
- Arduino 1.8.10
- Open On-Chip Debugger 0.10.0+dev-00399-g09076d10 (2018-04-12-15:51) installed via `homebrew`

**Comment by technoblogy** [comment]
I get the same problem. Is there any progress on this?

**Comment by racerxdl** [comment]
Same on linux, although the openocd is installed in my system.
